#!/usr/bin/env bash

: '
List gds files and folders as one would with ls

This script does the following
1. Check if access token and base url exist
2. Prints the list of files and folders
'

set -euo pipefail

###########
# FUNCTIONS
###########

## Getters

check_gds(){
  : '
  Sub function, before we continue, make sure that the argument starts with gds://
  '

  # Local vars
  local scheme

  scheme="$(python3 -c "from urllib.parse import urlparse; print(urlparse(\"${gds_path}\").scheme)")"

  # Function doesn't output anything, just a non-zero return value if the scheme variable is not gds
  if [[ ! "${scheme}" == "gds" ]]; then
    return 1
  fi
}

###########ICA-ICA-LAZY SETUP ########################################

if [[ -z "${ICA_ICA_LAZY_HOME-}" ]]; then
  echo "Error - please ensure env var 'ICA_ICA_LAZY_HOME' is set" 1>&2
  exit 1
fi

if [[ -d "${ICA_ICA_LAZY_HOME}/internal-functions" ]]; then
  for f in "${ICA_ICA_LAZY_HOME}/internal-functions/"*".sh"; do
      # shellcheck source=../internal-functions/*.sh
      source "$f"
  done
fi

##########END ICA-ICA-LAZY SETUP ####################################

#######
# SETUP
#######

if [[ -z "${ICA_BASE_URL-}" ]]; then
    echo "Error: Need to set var \"ICA_BASE_URL\"" 1>&2
    exit 1
fi

if [[ -z "${ICA_ACCESS_TOKEN-}" ]]; then
    echo "Error: Need to set var \"ICA_ACCESS_TOKEN\"" 1>&2
    echo "Error: Please first run ica-context-switcher" 1>&2
    exit 1
fi

# Check token expiry
check_token_expiry "${ICA_ACCESS_TOKEN}"

if [[ -z "${1:-}" ]]; then
    exit
fi

########
# INPUTS
########
gds_path="${1:-gds://}"
# Strip quotes from name
gds_path="${gds_path%\"}"
gds_path="${gds_path#\"}"

# Start of workflow

# Check prompt starts with gds
if ! check_gds; then
  : '
  Nothing to return - we just echo "gds://"
  '
  echo "gds://"
fi

# Get the volume
volume_name="$(get_volume_name "${gds_path}")"

if [[ "${volume_name}" == "" ]]; then
  print_volumes "${ICA_BASE_URL}" "${ICA_ACCESS_TOKEN}"
  exit
fi

# Check volume exists - if not print all volumes
if ! check_volume "${volume_name}" "${ICA_BASE_URL}" "${ICA_ACCESS_TOKEN}"; then
  print_volumes "${ICA_BASE_URL}" "${ICA_ACCESS_TOKEN}"
  exit
fi

# Get the path
gds_path_attr="$(get_path "${gds_path}")"

# Print from
if ! check_path_is_folder "${volume_name}" "${gds_path_attr}" "${ICA_BASE_URL}" "${ICA_ACCESS_TOKEN}"; then
  print_files_and_subfolders "${volume_name}" "$(get_parent_path "${gds_path_attr}")" "${ICA_BASE_URL}" "${ICA_ACCESS_TOKEN}"
else
  print_files_and_subfolders "${volume_name}" "${gds_path_attr}" "${ICA_BASE_URL}" "${ICA_ACCESS_TOKEN}"
fi
